# Generated by Django 2.2.3 on 2019-08-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('occupation', models.CharField(max_length=250)),
            ],
        ),
    ]
